In [1]:
import tensorflow as tf

In [7]:
a = tf.ones((3, 3))
b = tf.ones((3, 3))
c = tf.ones((3, 3))

ar, br, cr = tf.while_loop(
  cond=lambda a, b, c: tf.reduce_mean(a) < 5, 
  body=lambda a, b, c: (a + b + c, b, c),
  loop_vars=(a, b, c))

state = tf.constant([
  [1, 1, 1, 0, 0],
  [1, 1, 0, 0, 0],
  [1, 0, 0, 0, 0],
], dtype=tf.float32)

seq_len = tf.constant([3, 2, 1])
max_len = tf.reduce_max(seq_len)

def toi32(x):
  return tf.cast(x, tf.int32)

def times2(x):
  return x * 2

def update(st, sl, t, times2):
  return st

# final_t, final_state, _ = tf.while_loop(
#   cond=lambda t, st, sl: t < max_len,
#   body=lambda t, st, sl: (t + 1, st + 2.0 * tf.one_hot(toi32(t < seq_len) * t - toi32(t >= seq_len), st.shape[1]), sl),
#   loop_vars=(0, state, seq_len))

final_t, final_state, _ = tf.while_loop(
  cond=lambda t, st, sl: t < max_len,
  body=lambda t, st, sl: (t + 1, update(st, sl, t, times2), sl),
  loop_vars=(0, state, seq_len))

In [10]:
with tf.Session() as sess:
  print('while loop:')
  av, bv, cv = sess.run([ar, br, cr])
  print(av)
  print(bv)
  print(cv)
  
  print('rnn loop:')
  tv, sv = sess.run([final_t, final_state])
  print(tv)
  print(sv)

while loop:
[[ 5.  5.  5.]
 [ 5.  5.  5.]
 [ 5.  5.  5.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
rnn loop:
3
[[ 1.  1.  1.  0.  0.]
 [ 1.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]]
